remote_theme: vsoch/mkdocs-jekyll
plugins:
- jekyll-remote-theme

title: infomatico
email: elias.pereira@sertao.ifrs.edu.br
author: Elias Pereira
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

markdown: kramdown

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"