remote_theme: vsoch/mkdocs-jekyll
plugins:
- jekyll-remote-theme

title: infomatico
email: elias.pereira@sertao.ifrs.edu.br
author: Elias Pereira
description: infomatico

markdown: kramdown

defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page

  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"