theme: material
site_name: infomatico
site_author: Elias Pereira
site_description: infomatico

nav:
- home: index.md
- samba4:
  - ADDC:
    - Install & provision ADDC 4.19.x: install-provision-samba4.md
    - Backup & restore: backup-and-restore.md
  - Fileserver:
    - Choosing idmap backend: samba4_idmap_backend.md
- freeradius: freeradius.md
- devOps: devops.md
- proxmox: proxmox.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
