theme: material
site_name: infomatico
site_author: Elias Pereira
site_description: infomatico

nav:
- home: index.md
- samba4:
  - ADDC:
    - Install & provision ADDC 4.19.x: samba4_install_provision.md
    - Backup & restore: samba4_backup-and-restore.md
  - Fileserver:
    - Choosing idmap backend: samba4_idmap_backend.md
- freeradius: freeradius.md
- devOps: devops.md
- proxmox:
  - Migration from non cluster pve to another: pve_migration.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
